# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  languageName: English
  weight: 1
  contentDir: content/en
  #title: Computational Science Lab
  params:
    description: "Computational Science Lab"
    locale:
      date_format: 'January 2, 2006'   # 例: May 26, 2026

ja:
  languageCode: ja
  languageName: 日本語
  weight: 2
  contentDir: content/ja
  #title: 計算科学研究室
  params:
    description: "計算科学研究室"
    locale:
      date_format: '2006年01月02日'   # 例: 2026年05月26日


# Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
